### ISSUE TITLE
Hardcoded path in repetierHost configuration

### ISSUE THREAD

**Issue by Lucassifoni** [Tropicao/udelta-rework-repetier#4]
Hi,
Your home path /home/rock went into your distributables, and should be changed with the correct env value upon installation in repetier settings.

**Comment by Tropicao** [comment]
Hi,
thank you for the report.

**Comment by Tropicao** [comment]
Hi,
thank you for the report. What disturbs me a bit is that "rock" is not the user on my personnal distrib. It seems to be only used on configuration xml files and wrapper scripts, but I will make sure that setting it properly does not break Repetier. I will get back to this issue when fixed.

**Comment by Tropicao** [comment]
@Lucassifoni Fixed on master, tested for Debian configuration
